# fast-enter keybinds
[[mgr.prepend_keymap]]
on   = "<Right>"
run  = "plugin fast-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on   = "l"
run  = "plugin fast-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on   = "<Enter>"
run  = "plugin fast-enter"
desc = "Enter the child directory, or open the file"


# Bookmark keybinds
[[mgr.prepend_keymap]]
on = [ "m" ]
run = "plugin bookmarks save"
desc = "Save current position as a bookmark"

[[mgr.prepend_keymap]]
on = [ "`" ]
run = "plugin bookmarks jump"
desc = "Jump to a bookmark"

[[mgr.prepend_keymap]]
on = [ "b", "d" ]
run = "plugin bookmarks delete"
desc = "Delete a bookmark"

[[mgr.prepend_keymap]]
on = [ "b", "D" ]
run = "plugin bookmarks delete_all"
desc = "Delete all bookmarks"

# g key keybinds
[[mgr.prepend_keymap]]
on = [ "g", "d" ]
run  = "cd ~/Documents"
desc = "Cd to ~/Documents"

[[mgr.prepend_keymap]]
on   = [ "g", "D" ]
run  = "cd ~/Downloads"
desc = "Cd to ~/Downloads"

[[mgr.prepend_keymap]]
on   = [ "g", "c" ]
run  = "cd ~/dotfiles/"
desc = "Cd to ~/dotfile"

[[mgr.prepend_keymap]]
on   = [ "g", "p" ]
run  = "cd ~/Pictures"
desc = "Cd to ~/Pictures"

[[mgr.prepend_keymap]]
on   = [ "g", "<Backspace>" ]
run  = "cd --interactive"
#desc = "Jump interactively"

[[mgr.prepend_keymap]]
on = [ ".", "s" ]
run  = "plugin what-size"
desc = "Calc size of selection or cwd" 

# Lazy-git plugin keybinds
[[mgr.prepend_keymap]]
on   = [ "g", "i" ]
run  = "plugin lazygit"
desc = "run lazygit"

# Smart-filter plugin keybinds
[[mgr.prepend_keymap]]
on   = "f"
run  = "plugin smart-filter"
desc = "Smart filter"

[[mgr.prepend_keymap]]
on   = [ "g", "l" ]
run  = "plugin open-git-remote"
desc = "Open git remote URL in browser"
